[test]
coverage = true
coverageReporter = ["text"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/_fixtures_handlers/**",
  "**/_fixtures_proto/**",
  "**/tests/_studio_fixtures/**",
  "**/tests/fixtures/**",
]
