/**
 * Per-project schema emitters (specs/extensions.md §5.2).
 *
 * Pure functions: they emit the generated entry documents (project.schema.json and
 * document.schema.json) from already-resolved, project-relative fragment paths. All composition is
 * standard JSON Schema 2020-12:
 *
 * - A plain `allOf` over fragment `$ref`s, closed with `unevaluatedProperties: false`;
 * - The two well-known union resources (`PROJECT_FIELDS_SCHEMA_ID`, `DOCUMENT_PATHS_SCHEMA_ID`)
 *   re-embedded under `$defs` with their canonical `$id`s, carrying the _effective_ unions.
 *   Compound-document `$id` resolution makes every fragment's `$ref` to those URIs land on the
 *   entry document's embed instead of the shipped defaults — the override mechanism.
 *
 * Inside the embeds all refs are canonical URIs (never relative paths): a `$ref` inside a resource
 * with an absolute `$id` resolves against that `$id`. Relative `./node_modules/...` paths appear
 * only in the entry document's own `allOf`/`$ref`, resolved against the file location. Hosts
 * validating with ajv should inject an `$id` set to the entry file's URL at load time so those
 * relative refs resolve (the committed files stay machine-path-free).
 */

import {
  DOCUMENT_PATHS_SCHEMA_ID,
  PROJECT_FIELDS_SCHEMA_ID,
  documentPathsCoreMembers,
} from "../defs/field-schema.schema";

export { DOCUMENT_PATHS_SCHEMA_ID, PROJECT_FIELDS_SCHEMA_ID } from "../defs/field-schema.schema";

/** The canonical $id of the core project fragment. */
export const PROJECT_CORE_SCHEMA_ID = "https://jxsuite.com/schema/project/core/v2";

export const GENERATED_SCHEMA_COMMENT =
  "Generated by `jx schema` from project.json#/extensions — do not edit.";

export interface ProjectSchemaInputs {
  /**
   * Project-relative path of the core fragment, e.g.
   * "./node_modules/@jxsuite/schema/schemas/project.core.schema.json".
   */
  corePath: string;
  /** Project-relative extension fragment paths, in extension declaration order. */
  fragments: string[];
  /**
   * Additional field-union members beyond the core field shape and RelationshipRef, as canonical
   * "uri#/pointer" refs (e.g. a connector's column extras). Never relative paths — they resolve
   * against the embed's $id.
   */
  fieldSchemaRefs?: string[];
}

/** Emit the `project.schema.json` entry document for a project. */
export function emitProjectSchema(inputs: ProjectSchemaInputs): Record<string, unknown> {
  const { corePath, fragments, fieldSchemaRefs = [] } = inputs;
  return {
    $comment: GENERATED_SCHEMA_COMMENT,
    $defs: {
      Fields: {
        $id: PROJECT_FIELDS_SCHEMA_ID,
        anyOf: [
          { $ref: `${PROJECT_CORE_SCHEMA_ID}#/$defs/JxFieldSchema` },
          { $ref: `${PROJECT_CORE_SCHEMA_ID}#/$defs/RelationshipRef` },
          ...fieldSchemaRefs.map((ref) => ({ $ref: ref })),
        ],
      },
    },
    $schema: "https://json-schema.org/draft/2020-12/schema",
    allOf: [{ $ref: corePath }, ...fragments.map((ref) => ({ $ref: ref }))],
    type: "object",
    unevaluatedProperties: false,
  };
}

// ─── Generic bundler (specs/extensions.md §5.4) ──────────────────────────────

/** Injected JSON loader for {@link bundleSchema} — receives a normalized, slash-separated path. */
export type SchemaJsonLoader = (path: string) => Promise<Record<string, unknown>>;

/**
 * Bundle an entry document into a single self-contained compound schema for hosts that cannot fetch
 * files (editor schema registration, cloud studio). Every relative-path `$ref` target is loaded
 * through the injected loader and embedded under the entry's `$defs`, keyed by its `$id` (or a
 * generated `urn:jx:bundled:*` one when the file declares none); the referencing `$ref`s are
 * rewritten to those canonical URIs. Resource boundaries are preserved: embedded resources keep
 * their `$id`s, refs inside an embedded absolute-`$id` resource are canonical and stay untouched,
 * and a resource whose `$id` is already present in the compound document is not embedded twice.
 *
 * @param {Record<string, unknown>} entry - The entry document (e.g. a parsed project.schema.json)
 * @param {SchemaJsonLoader} loadJson - Loader for `$ref` target files (host-restricted)
 * @param {string} baseDir - Directory the entry document's relative refs resolve against
 * @param {string[]} [alsoEmbed] - Relative paths of resources to embed even though no path-`$ref`
 *   reaches them, because they are referenced only by canonical `$id` (a document fragment whose
 *   `$defs` feed the paths union). Without this they would stay dangling.
 * @returns {Promise<Record<string, unknown>>} A new, self-contained schema (the input is not
 *   mutated)
 */
export async function bundleSchema(
  entry: Record<string, unknown>,
  loadJson: SchemaJsonLoader,
  baseDir: string,
  alsoEmbed: string[] = [],
): Promise<Record<string, unknown>> {
  const bundled = structuredClone(entry);
  const embeddedByPath = new Map<string, string>();
  const embeddedIds = new Set<string>();
  collectResourceIds(bundled, embeddedIds);
  let generatedCount = 0;

  /** Ordered queue of embeds so $defs insertion happens after the entry walk (stable output). */
  const embed = async (path: string): Promise<string> => {
    const normalized = normalizeSchemaPath(path);
    const prior = embeddedByPath.get(normalized);
    if (prior !== undefined) {
      return prior;
    }
    let resource: Record<string, unknown>;
    try {
      resource = structuredClone(await loadJson(normalized));
    } catch (error) {
      throw new Error(
        `bundleSchema: cannot load $ref target "${normalized}": ${errorText(error)}`,
        { cause: error },
      );
    }
    const ownId =
      typeof resource.$id === "string" && hasUriScheme(resource.$id) ? resource.$id : null;
    generatedCount += ownId === null ? 1 : 0;
    const id = ownId ?? `urn:jx:bundled:${generatedCount}`;
    embeddedByPath.set(normalized, id);
    if (embeddedIds.has(id)) {
      // The canonical resource is already part of the compound document — refs land on it.
      return id;
    }
    embeddedIds.add(id);
    resource.$id = id;
    await rewrite(resource, schemaDirOf(normalized), true);
    const defs = (bundled.$defs ??= {}) as Record<string, unknown>;
    defs[id] = resource;
    return id;
  };

  /**
   * Walk a (sub)schema rewriting relative-path `$ref`s. `fileDir` is the directory relative refs
   * resolve against, or null inside an embedded absolute-`$id` resource (canonical scope).
   */
  const rewrite = async (node: unknown, fileDir: string | null, isRoot = false): Promise<void> => {
    if (Array.isArray(node)) {
      for (const item of node) {
        await rewrite(item, fileDir);
      }
      return;
    }
    if (node === null || typeof node !== "object") {
      return;
    }
    const obj = node as Record<string, unknown>;
    let scope = fileDir;
    if (!isRoot && typeof obj.$id === "string" && hasUriScheme(obj.$id)) {
      // Entering an embedded resource with a canonical $id: refs inside resolve against that
      // $id (never the file location), so there is nothing to inline.
      scope = null;
    }
    const ref = obj.$ref;
    if (typeof ref === "string" && scope !== null && !ref.startsWith("#") && !hasUriScheme(ref)) {
      const hashIndex = ref.indexOf("#");
      const target = hashIndex === -1 ? ref : ref.slice(0, hashIndex);
      const fragment = hashIndex === -1 ? "" : ref.slice(hashIndex);
      if (target) {
        const id = await embed(`${scope}/${target}`);
        obj.$ref = `${id}${fragment}`;
      }
    }
    for (const value of Object.values(obj)) {
      await rewrite(value, scope);
    }
  };

  await rewrite(bundled, normalizeSchemaPath(baseDir), true);
  for (const path of alsoEmbed) {
    await embed(`${normalizeSchemaPath(baseDir)}/${path}`);
  }
  return bundled;
}

// ─── Single-resource flattening (specs/extensions.md §5.4) ───────────────────

/**
 * Keywords whose value is a single subschema (or, for draft-07 tuple `items`, an array of them).
 * The flattener walks ONLY these keyword positions, never every object key: `examples`, `default`,
 * `const` and `enum` hold arbitrary instance data, and Jx document examples legitimately contain
 * `$ref` strings (`#/state/cart`) that must survive untouched.
 */
const SINGLE_SUBSCHEMA_KEYWORDS = [
  "additionalItems",
  "additionalProperties",
  "contains",
  "contentSchema",
  "else",
  "if",
  "items",
  "not",
  "propertyNames",
  "then",
  "unevaluatedItems",
  "unevaluatedProperties",
] as const;

/** Keywords whose value maps names to subschemas. */
const MAP_SUBSCHEMA_KEYWORDS = [
  "$defs",
  "definitions",
  "dependencies",
  "dependentSchemas",
  "patternProperties",
  "properties",
] as const;

/** Keywords whose value is an array of subschemas. */
const LIST_SUBSCHEMA_KEYWORDS = ["allOf", "anyOf", "oneOf", "prefixItems"] as const;

/** True for a plain object node (a candidate subschema); booleans and arrays are not. */
function isSchemaObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Escape a `$defs` key for use as a JSON Pointer segment (RFC 6901). */
function escapePointerSegment(segment: string): string {
  return segment.replaceAll("~", "~0").replaceAll("/", "~1");
}

/**
 * Walk the known subschema keyword positions of `node`.
 *
 * @param {Record<string, unknown>} node - The schema object to walk
 * @param {string} pointer - JSON Pointer of `node` within the document
 * @yields {[Record<string, unknown>, string]} Each subschema paired with its own JSON Pointer
 */
function* subschemaEntries(
  node: Record<string, unknown>,
  pointer: string,
): Generator<[Record<string, unknown>, string]> {
  for (const keyword of SINGLE_SUBSCHEMA_KEYWORDS) {
    const value = node[keyword];
    if (Array.isArray(value)) {
      for (const [index, item] of value.entries()) {
        if (isSchemaObject(item)) {
          yield [item, `${pointer}/${keyword}/${index}`];
        }
      }
    } else if (isSchemaObject(value)) {
      yield [value, `${pointer}/${keyword}`];
    }
  }
  for (const keyword of MAP_SUBSCHEMA_KEYWORDS) {
    const value = node[keyword];
    if (!isSchemaObject(value)) {
      continue;
    }
    for (const [name, item] of Object.entries(value)) {
      if (isSchemaObject(item)) {
        yield [item, `${pointer}/${keyword}/${escapePointerSegment(name)}`];
      }
    }
  }
  for (const keyword of LIST_SUBSCHEMA_KEYWORDS) {
    const value = node[keyword];
    if (!Array.isArray(value)) {
      continue;
    }
    for (const [index, item] of value.entries()) {
      if (isSchemaObject(item)) {
        yield [item, `${pointer}/${keyword}/${index}`];
      }
    }
  }
}

/**
 * A readable, collision-free `$defs` key for an embedded resource's `$id`: drop the scheme, the
 * authority, and the conventional `schema/` namespace segment, then join the remainder with dashes
 * (`https://jxsuite.com/schema/project/core/v2` → `project-core-v2`, `urn:jx:bundled:1` →
 * `jx-bundled-1`). Collisions get a numeric suffix, so output stays deterministic given the
 * emitters' stable `$defs` order.
 *
 * @param {string} id - The resource's canonical `$id`
 * @param {Set<string>} used - Keys already taken in the target `$defs` (mutated)
 * @returns {string}
 */
function slugForSchemaId(id: string, used: Set<string>): string {
  let rest = id.replace(/^[a-zA-Z][a-zA-Z\d+.-]*:/, "");
  if (rest.startsWith("//")) {
    const slash = rest.indexOf("/", 2);
    rest = slash === -1 ? "" : rest.slice(slash + 1);
  }
  rest = rest.replace(/^schema\//, "");
  const base =
    rest
      .split(/[^a-zA-Z0-9]+/)
      .filter(Boolean)
      .join("-") || "resource";
  let key = base;
  for (let n = 2; used.has(key); n += 1) {
    key = `${base}-${n}`;
  }
  used.add(key);
  return key;
}

/**
 * Collapse a bundled compound document into a SINGLE schema resource: embedded resources are
 * rekeyed from their canonical `$id`s to readable `$defs` slugs, their `$id`s are dropped, and
 * every `$ref` becomes a root-relative JSON Pointer (`#/$defs/project-core-v2/$defs/StyleObject`).
 *
 * Why this is required rather than cosmetic: VS Code's JSON language service (and Monaco, which
 * embeds it) implements neither half of compound-document resolution. It resolves a `#/pointer` ref
 * against the DOCUMENT ROOT — never re-based on an enclosing `$id` — so a fragment's own
 * `#/$defs/StyleObject` reports "can not be resolved"; and it treats any ref with a non-empty part
 * before `#` as EXTERNAL, fetching `https://jxsuite.com/schema/...` over the network instead of
 * matching the embedded resource, which fails offline and (when it succeeds) silently substitutes
 * the shipped defaults for the project's effective unions. Root-pointer-only refs are the one form
 * every consumer resolves identically — ajv, the language service, and Monaco alike.
 *
 * `$id` shadowing (§5.3) still decides the outcome; it is simply resolved AT FLATTEN TIME, since
 * refs to a shadowed `$id` rewrite to the pointer of the entry document's embed.
 *
 * @param {Record<string, unknown>} entry - A bundled compound document (output of
 *   {@link bundleSchema})
 * @returns {Record<string, unknown>} A new single-resource schema (the input is not mutated)
 */
export function flattenSchema(entry: Record<string, unknown>): Record<string, unknown> {
  const flat = structuredClone(entry);

  // 1. Rekey URI-keyed `$defs` entries to readable slugs (pointers address them by key).
  if (isSchemaObject(flat.$defs)) {
    const used = new Set(Object.keys(flat.$defs).filter((key) => !hasUriScheme(key)));
    const renamed: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(flat.$defs)) {
      const id = isSchemaObject(value) && typeof value.$id === "string" ? value.$id : key;
      renamed[hasUriScheme(key) ? slugForSchemaId(id, used) : key] = value;
    }
    flat.$defs = renamed;
  }

  // 2. Map each embedded resource's `$id` to its pointer here (first wins, as the bundler embeds).
  const idToPointer = new Map<string, string>();
  const scan = (node: Record<string, unknown>, pointer: string): void => {
    const { $id } = node;
    if (typeof $id === "string" && hasUriScheme($id) && !idToPointer.has($id)) {
      idToPointer.set($id, pointer);
    }
    for (const [child, childPointer] of subschemaEntries(node, pointer)) {
      scan(child, childPointer);
    }
  };
  scan(flat, "#");

  // 3. Rewrite refs against the enclosing resource, then dissolve the resource boundary.
  const rewrite = (node: Record<string, unknown>, scope: string): void => {
    let inner = scope;
    const { $id } = node;
    if (typeof $id === "string" && hasUriScheme($id)) {
      inner = idToPointer.get($id) ?? scope;
      if (inner !== "#") {
        // The root keeps its identity; nested resources must not remain ref targets.
        delete node.$id;
      }
    }
    const ref = node.$ref;
    if (typeof ref === "string") {
      const hashIndex = ref.indexOf("#");
      const target = hashIndex === -1 ? ref : ref.slice(0, hashIndex);
      const fragment = hashIndex === -1 ? "" : ref.slice(hashIndex + 1);
      if (target === "") {
        // A local pointer resolves against the resource it appears in, not the file.
        if (fragment.startsWith("/")) {
          node.$ref = `${inner}${fragment}`;
        }
      } else {
        const base = idToPointer.get(target);
        if (base !== undefined) {
          node.$ref = fragment ? `${base}${fragment}` : base;
        }
      }
    }
    for (const [child] of subschemaEntries(node, inner)) {
      rewrite(child, inner);
    }
  };
  rewrite(flat, "#");
  return flat;
}

/** Collect every absolute `$id` already present in a document (embeds like the field union). */
function collectResourceIds(node: unknown, out: Set<string>): void {
  if (Array.isArray(node)) {
    for (const item of node) {
      collectResourceIds(item, out);
    }
    return;
  }
  if (node === null || typeof node !== "object") {
    return;
  }
  const obj = node as Record<string, unknown>;
  if (typeof obj.$id === "string" && hasUriScheme(obj.$id)) {
    out.add(obj.$id);
  }
  for (const value of Object.values(obj)) {
    collectResourceIds(value, out);
  }
}

/** True when a ref/id carries a URI scheme (https:, urn:, file:) — i.e. is not a relative path. */
function hasUriScheme(ref: string): boolean {
  return /^[a-zA-Z][a-zA-Z\d+.-]*:/.test(ref);
}

/** Normalize a path to forward slashes, resolving "." and ".." segments (environment-agnostic). */
function normalizeSchemaPath(path: string): string {
  const slashed = path.replaceAll("\\", "/");
  const absolute = slashed.startsWith("/");
  const parts: string[] = [];
  for (const segment of slashed.split("/")) {
    if (segment === "" || segment === ".") {
      continue;
    }
    if (segment === "..") {
      if (parts.length > 0 && parts.at(-1) !== "..") {
        parts.pop();
      } else if (!absolute) {
        parts.push("..");
      }
      continue;
    }
    parts.push(segment);
  }
  return (absolute ? "/" : "") + parts.join("/");
}

/** The directory portion of a normalized schema path ("." when there is none). */
function schemaDirOf(path: string): string {
  const index = path.lastIndexOf("/");
  if (index === -1) {
    return ".";
  }
  return index === 0 ? "/" : path.slice(0, index);
}

function errorText(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export interface DocumentSchemaInputs {
  /**
   * Project-relative path of the core document schema, e.g.
   * "./node_modules/@jxsuite/schema/schema.json".
   */
  corePath: string;
  /** Canonical "uri#/pointer" refs unioned into the paths resource, in declaration order. */
  pathsValueRefs: string[];
}

/**
 * Emit the `document.schema.json` entry document for a project.
 *
 * The core reference goes in a single-member `allOf`, never a root-level `$ref`. They are
 * equivalent to a compliant validator, but VS Code's JSON language service resolves a `$ref` by
 * SHALLOW-MERGING the target's keys into the referencing node — from the root, that overwrites the
 * root's own `$defs` with the core resource's `$defs`, and every later `#/$defs/<embed>/...`
 * pointer stops resolving. Wrapping in `allOf` keeps the merge target off the root.
 *
 * @param {DocumentSchemaInputs} inputs - Core path and the contributed paths-union refs
 * @returns {Record<string, unknown>}
 */
export function emitDocumentSchema(inputs: DocumentSchemaInputs): Record<string, unknown> {
  const { corePath, pathsValueRefs } = inputs;
  return {
    $comment: GENERATED_SCHEMA_COMMENT,
    $defs: {
      /* The EFFECTIVE paths union: the core source shapes plus every extension-contributed one.
         Carrying the core members here (rather than leaving them to the core schema) is what makes
         the override additive — this embed shadows the shipped default by $id, so anything it omits
         stops validating. Mirrors the field union in emitProjectSchema, which names its core
         members the same way. */
      PathsValue: {
        $id: DOCUMENT_PATHS_SCHEMA_ID,
        anyOf: [...documentPathsCoreMembers, ...pathsValueRefs.map((ref) => ({ $ref: ref }))],
      },
    },
    $schema: "https://json-schema.org/draft/2020-12/schema",
    allOf: [{ $ref: corePath }],
  };
}

// ─── Composition (specs/extensions.md §5.2) ──────────────────────────────────

/** Loader-resolvable refs to one extension's shipped schema fragments, as its manifest names them. */
export interface ExtensionFragmentRefs {
  /** Project fragment — plain `properties` for the extension's section keys. */
  project?: string | undefined;
  /** Document fragment — its `$defs` become `$paths` source-union members. */
  document?: string | undefined;
  /** Fields fragment — its `$defs` become Field-schema union members. */
  fields?: string | undefined;
}

export interface ComposeProjectSchemasInputs {
  /** Ref to the core project fragment (`@jxsuite/schema/schemas/project.core.schema.json`). */
  coreProjectRef: string;
  /** Ref to the core document schema (`@jxsuite/schema/schema.json`). */
  coreDocumentRef: string;
  /** Enabled extensions in registry order; each contributes the fragments it ships. */
  extensions: ExtensionFragmentRefs[];
  /** Loads a ref's JSON. Every ref above and every `$ref` inside resolves through this ALONE. */
  loadJson: SchemaJsonLoader;
  /** Directory the refs resolve against ("" for hosts addressing by bare specifier). */
  baseDir: string;
}

/**
 * Compose a project's two committed entry documents from the core schemas and its enabled
 * extensions' fragments — bundled, then flattened to root JSON pointers (§5.2/§5.4).
 *
 * Host-agnostic by construction: every file it needs arrives through `loadJson`, so the same
 * composition runs over a filesystem (`jx schema`) and over a virtual tree of bundled artifacts
 * (the cloud session, which has no `node_modules` and no filesystem). That shared path is the point
 * — a project's schemas must not depend on which host generated them.
 *
 * @param {ComposeProjectSchemasInputs} inputs - Core refs, extension fragments, loader, base
 * @returns {Promise<{ project: Record<string, unknown>; document: Record<string, unknown> }>} The
 *   self-contained entry documents, ready to write or to hand an editor
 */
export async function composeProjectSchemas(inputs: ComposeProjectSchemasInputs): Promise<{
  project: Record<string, unknown>;
  document: Record<string, unknown>;
}> {
  const { baseDir, coreDocumentRef, coreProjectRef, extensions, loadJson } = inputs;

  const fragments: string[] = [];
  const pathsValueRefs: string[] = [];
  const documentFragments: string[] = [];
  const fieldSchemaRefs: string[] = [];
  for (const ext of extensions) {
    if (ext.project) {
      fragments.push(ext.project);
    }
    if (ext.document) {
      const documentRefs = await fragmentDefsRefs(ext.document, loadJson, baseDir);
      pathsValueRefs.push(...documentRefs);
      /* The paths union names this fragment's shapes by canonical $id only, so the bundler needs
         the path handed to it explicitly or those refs stay dangling. A fragment that contributed
         nothing (no $id, or no $defs) is left out rather than embedded unreferenced. */
      if (documentRefs.length > 0) {
        documentFragments.push(ext.document);
      }
    }
    // The `schemas.fields` manifest convention: a fragment whose $defs members are extension
    // Field extras, unioned into the per-project field resource (specs/extensions.md §5.3).
    if (ext.fields) {
      fieldSchemaRefs.push(...(await fragmentDefsRefs(ext.fields, loadJson, baseDir)));
      fragments.push(ext.fields);
    }
  }

  // Bundle then flatten: the emitted relative refs are an intermediate form only.
  const projectEntry = emitProjectSchema({ corePath: coreProjectRef, fieldSchemaRefs, fragments });
  const documentEntry = emitDocumentSchema({ corePath: coreDocumentRef, pathsValueRefs });
  return {
    document: flattenSchema(
      await bundleSchema(documentEntry, loadJson, baseDir, documentFragments),
    ),
    project: flattenSchema(await bundleSchema(projectEntry, loadJson, baseDir)),
  };
}

/**
 * Canonical "uri#/pointer" refs into a fragment's `$defs` shapes: one per `$defs` entry, addressed
 * by the fragment's own `$id` (refs inside the entry document's embeds resolve against canonical
 * URIs, never file paths). An `$id`-less or `$defs`-less fragment contributes no union members —
 * that is simply the shape of a fragment declaring only `properties`.
 *
 * An UNREADABLE fragment contributes nothing here but still fails the composition, because the
 * bundler goes on to embed the same ref and throws. That is deliberate: silently dropping it would
 * emit an entry document that under-validates the project with nothing to show for it. A host that
 * cannot supply an extension's fragments must leave that extension out of `extensions` entirely —
 * which is exactly what the cloud session does for packages it does not bundle.
 *
 * @param {string} ref - Loader-resolvable ref to the fragment, relative to `baseDir`
 * @param {SchemaJsonLoader} loadJson - The host's loader
 * @param {string} baseDir - Directory the ref resolves against
 * @returns {Promise<string[]>} One ref per `$defs` member, in declaration order
 */
async function fragmentDefsRefs(
  ref: string,
  loadJson: SchemaJsonLoader,
  baseDir: string,
): Promise<string[]> {
  let fragment: { $id?: unknown; $defs?: Record<string, unknown> };
  try {
    fragment = await loadJson(normalizeSchemaPath(`${normalizeSchemaPath(baseDir)}/${ref}`));
  } catch {
    return [];
  }
  const { $id } = fragment;
  if (typeof $id !== "string" || !fragment.$defs) {
    return [];
  }
  return Object.keys(fragment.$defs).map((name) => `${$id}#/$defs/${name}`);
}
