/**
 * Per-project schema emitters (specs/extensions.md §5.2).
 *
 * Pure functions: they emit the generated entry documents (project.schema.json and
 * document.schema.json) from already-resolved, project-relative fragment paths. All composition is
 * standard JSON Schema 2020-12:
 *
 * - A plain `allOf` over fragment `$ref`s, closed with `unevaluatedProperties: false`;
 * - The two well-known union resources (`PROJECT_FIELDS_SCHEMA_ID`, `DOCUMENT_PATHS_SCHEMA_ID`)
 *   re-embedded under `$defs` with their canonical `$id`s, carrying the _effective_ unions.
 *   Compound-document `$id` resolution makes every fragment's `$ref` to those URIs land on the
 *   entry document's embed instead of the shipped defaults — the override mechanism.
 *
 * Inside the embeds all refs are canonical URIs (never relative paths): a `$ref` inside a resource
 * with an absolute `$id` resolves against that `$id`. Relative `./node_modules/...` paths appear
 * only in the entry document's own `allOf`/`$ref`, resolved against the file location. Hosts
 * validating with ajv should inject an `$id` set to the entry file's URL at load time so those
 * relative refs resolve (the committed files stay machine-path-free).
 */

import { DOCUMENT_PATHS_SCHEMA_ID, PROJECT_FIELDS_SCHEMA_ID } from "../defs/field-schema.schema";

export { DOCUMENT_PATHS_SCHEMA_ID, PROJECT_FIELDS_SCHEMA_ID } from "../defs/field-schema.schema";

/** The canonical $id of the core project fragment. */
export const PROJECT_CORE_SCHEMA_ID = "https://jxsuite.com/schema/project/core/v2";

export const GENERATED_SCHEMA_COMMENT =
  "Generated by `jx schema` from project.json#/extensions — do not edit.";

export interface ProjectSchemaInputs {
  /**
   * Project-relative path of the core fragment, e.g.
   * "./node_modules/@jxsuite/schema/schemas/project.core.schema.json".
   */
  corePath: string;
  /** Project-relative extension fragment paths, in extension declaration order. */
  fragments: string[];
  /**
   * Additional field-union members beyond the core field shape and RelationshipRef, as canonical
   * "uri#/pointer" refs (e.g. a connector's column extras). Never relative paths — they resolve
   * against the embed's $id.
   */
  fieldSchemaRefs?: string[];
}

/** Emit the `project.schema.json` entry document for a project. */
export function emitProjectSchema(inputs: ProjectSchemaInputs): Record<string, unknown> {
  const { corePath, fragments, fieldSchemaRefs = [] } = inputs;
  return {
    $comment: GENERATED_SCHEMA_COMMENT,
    $defs: {
      Fields: {
        $id: PROJECT_FIELDS_SCHEMA_ID,
        anyOf: [
          { $ref: `${PROJECT_CORE_SCHEMA_ID}#/$defs/JxFieldSchema` },
          { $ref: `${PROJECT_CORE_SCHEMA_ID}#/$defs/RelationshipRef` },
          ...fieldSchemaRefs.map((ref) => ({ $ref: ref })),
        ],
      },
    },
    $schema: "https://json-schema.org/draft/2020-12/schema",
    allOf: [{ $ref: corePath }, ...fragments.map((ref) => ({ $ref: ref }))],
    type: "object",
    unevaluatedProperties: false,
  };
}

export interface DocumentSchemaInputs {
  /**
   * Project-relative path of the core document schema, e.g.
   * "./node_modules/@jxsuite/schema/schema.json".
   */
  corePath: string;
  /** Canonical "uri#/pointer" refs unioned into the paths resource, in declaration order. */
  pathsValueRefs: string[];
}

/** Emit the `document.schema.json` entry document for a project. */
export function emitDocumentSchema(inputs: DocumentSchemaInputs): Record<string, unknown> {
  const { corePath, pathsValueRefs } = inputs;
  return {
    $comment: GENERATED_SCHEMA_COMMENT,
    $defs: {
      // With no contributed paths shapes the embed stays permissive — core `$paths` forms
      // (arrays, values, $ref) are validated by the core schema itself.
      PathsValue:
        pathsValueRefs.length > 0
          ? {
              $id: DOCUMENT_PATHS_SCHEMA_ID,
              anyOf: pathsValueRefs.map((ref) => ({ $ref: ref })),
            }
          : { $id: DOCUMENT_PATHS_SCHEMA_ID },
    },
    $ref: corePath,
    $schema: "https://json-schema.org/draft/2020-12/schema",
  };
}
