// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class CodePanel extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      filename: "",
      badge: "",
    });
  }

  template() {
    const s = this.state;
    return html`
      <div
        class="code-panel-0"
      >
        <span
          class="code-panel-1"
        >${s.filename}</span>
        <span
          class="code-panel-2"
        >${s.badge}</span>
      </div>
      <div
        class="code-panel-3"
      >
        <slot
        ></slot>
      </div>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    const _slotted = Array.from(this.childNodes).filter(n => n.nodeType === 1 || (n.nodeType === 3 && n.textContent.trim()));
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
    const _slot = this.querySelector('slot');
    if (_slot && _slotted.length > 0) {
      for (const n of _slotted) _slot.before(n);
      _slot.remove();
    }
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('code-panel', CodePanel);
