// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class CtaButton extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      href: "/",
      label: "Click",
      variant: "primary",
      isPrimary: "${state.variant === 'primary'}",
    });
  }

  template() {
    const s = this.state;
    return html`
      <a
        href="${s.href}"
        class="cta-button-0"
        style="background-color: ${s.isPrimary ? 'var(--color-accent)' : 'transparent'}; color: ${s.isPrimary ? 'white' : 'var(--color-text-secondary)'}; border: ${s.isPrimary ? '1px solid transparent' : '1px solid var(--color-border)'}"
      >${s.label}</a>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('cta-button', CtaButton);
