// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class DocsSidebar extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
    });
  }

  template() {
    const s = this.state;
    return html`
      <div
        class="docs-sidebar-0"
      >
        Getting Started
      </div>
      <a
        href="/docs/getting-started"
        class="docs-sidebar-1"
      >
        Installation &amp; Setup
      </a>
      <div
        class="docs-sidebar-2"
      >
        Core Concepts
      </div>
      <a
        href="/docs/spec"
        class="docs-sidebar-3"
      >
        Spec Overview
      </a>
      <a
        href="/docs/components"
        class="docs-sidebar-4"
      >
        Component Model
      </a>
      <a
        href="/docs/reactivity"
        class="docs-sidebar-5"
      >
        Reactivity
      </a>
      <a
        href="/docs/styling"
        class="docs-sidebar-6"
      >
        Styling
      </a>
      <div
        class="docs-sidebar-7"
      >
        Architecture
      </div>
      <a
        href="/docs/site-architecture"
        class="docs-sidebar-8"
      >
        Site Architecture
      </a>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('docs-sidebar', DocsSidebar);
