// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class FeatureCard extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      icon: "",
      iconBg: "rgba(59, 130, 246, 0.1)",
      iconColor: "var(--color-accent)",
      iconSize: "0.6875rem",
      title: "",
      description: "",
    });
  }

  template() {
    const s = this.state;
    return html`
      <div
        class="feature-card-0"
        style="background-color: ${s.iconBg}; color: ${s.iconColor}; font-size: ${s.iconSize}"
      >${s.icon}</div>
      <h3
        class="feature-card-1"
      >${s.title}</h3>
      <p
        class="feature-card-2"
      >${s.description}</p>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('feature-card', FeatureCard);
