// Generated by @jxsuite/compiler — do not edit manually
// Source: InteractiveDemo
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class InteractiveDemo extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      activeTab: "source",
      count: 0,
    });

    this.state.increment = (s, e) => { s.count += 1; };

    this.state.reset = (s, e) => { s.count = 0; };
  }

  template() {
    const s = this.state;
    return html`
      <div
        class="interactive-demo-0"
      >
        <button
          class="interactive-demo-1"
          @click="${(e) => { s.activeTab = "source"; }}"
          style="border-bottom: ${s.activeTab === 'source' ? '2px solid var(--color-accent, #007bff)' : '2px solid transparent'}; font-weight: ${s.activeTab === 'source' ? '600' : '400'}; color: ${s.activeTab === 'source' ? 'var(--color-accent, #007bff)' : 'var(--color-text-secondary, #6c757d)'}"
        >Jx Source</button>
        <button
          class="interactive-demo-2"
          @click="${(e) => { s.activeTab = "compiled"; }}"
          style="border-bottom: ${s.activeTab === 'compiled' ? '2px solid var(--color-accent, #007bff)' : '2px solid transparent'}; font-weight: ${s.activeTab === 'compiled' ? '600' : '400'}; color: ${s.activeTab === 'compiled' ? 'var(--color-accent, #007bff)' : 'var(--color-text-secondary, #6c757d)'}"
        >Compiled</button>
        <button
          class="interactive-demo-3"
          @click="${(e) => { s.activeTab = "result"; }}"
          style="border-bottom: ${s.activeTab === 'result' ? '2px solid var(--color-accent, #007bff)' : '2px solid transparent'}; font-weight: ${s.activeTab === 'result' ? '600' : '400'}; color: ${s.activeTab === 'result' ? 'var(--color-accent, #007bff)' : 'var(--color-text-secondary, #6c757d)'}"
        >Result</button>
      </div>
      <div
        class="interactive-demo-4"
        style="display: ${s.activeTab === 'source' ? 'block' : 'none'}"
      >
        <pre
          class="interactive-demo-5"
        >
          <code
          >{
  "tagName": "my-counter",
  "state": {
    "count": 0,
    "increment": {
      "$expression": {
        "operator": "+=",
        "target": { "$ref": "#/state/count" },
        "value": 1
      }
    },
    "reset": {
      "$expression": {
        "operator": "=",
        "target": { "$ref": "#/state/count" },
        "value": 0
      }
    }
  },
  "children": [
    { "tagName": "span",
      "textContent": { "$ref": "#/state/count" } },
    { "tagName": "button", "textContent": "+",
      "onclick": { "$ref": "#/state/increment" } },
    { "tagName": "button", "textContent": "Reset",
      "onclick": { "$ref": "#/state/reset" } }
  ]
}</code>
        </pre>
      </div>
      <div
        class="interactive-demo-6"
        style="display: ${s.activeTab === 'compiled' ? 'block' : 'none'}"
      >
        <pre
          class="interactive-demo-7"
        >
          <code
          >// Generated by @jxsuite/compiler
import { reactive, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class MyCounter extends HTMLElement {
  constructor() {
    super();
    this.state = reactive({ count: 0 });

    // $expression → compiled handler
    this.state.increment = (s) => {
      s.count += 1;
    };
    this.state.reset = (s) => {
      s.count = 0;
    };
  }

  connectedCallback() {
    this.#dispose = effect(() =>
      render(this.template(), this)
    );
  }
}

customElements.define('my-counter', MyCounter);</code>
        </pre>
      </div>
      <div
        class="interactive-demo-8"
        style="display: ${s.activeTab === 'result' ? 'flex' : 'none'}"
      >
        <span
          class="interactive-demo-9"
        >${s.count}</span>
        <div
          class="interactive-demo-10"
        >
          <button
            class="interactive-demo-11"
            @click="${(e) => s.increment(s, e)}"
          >+</button>
          <button
            class="interactive-demo-12"
            @click="${(e) => s.reset(s, e)}"
          >Reset</button>
        </div>
        <p
          class="interactive-demo-13"
        >This counter is live — built from the JSON on the left.</p>
      </div>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('interactive-demo', InteractiveDemo);
