// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class PillarCard extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      icon: "{}",
      title: "Feature",
      description: "Description",
      features: "",
    });
  }

  template() {
    const s = this.state;
    return html`
      <div
        class="pillar-card-0"
      >${s.icon}</div>
      <h3
        class="pillar-card-1"
      >${s.title}</h3>
      <p
        class="pillar-card-2"
      >${s.description}</p>
      <div
        class="pillar-card-3"
      >${s.features}</div>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('pillar-card', PillarCard);
