// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class SectionLabel extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      text: "Label",
    });
  }

  template() {
    const s = this.state;
    return html`

    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('section-label', SectionLabel);
