// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class SiteFooter extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
    });
  }

  template() {
    const s = this.state;
    return html`
      <div
        class="site-footer-0"
      >
        <p
          class="site-footer-1"
        >
          Built with Jx Suite. MIT License.
        </p>
        <div
          class="site-footer-2"
        >
          <a
            href="/docs/getting-started"
            class="site-footer-3"
          >
            Docs
          </a>
          <a
            href="https://github.com/jxsuite/jx"
            target="_blank"
            rel="noopener noreferrer"
            class="site-footer-4"
          >
            GitHub
          </a>
        </div>
      </div>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('site-footer', SiteFooter);
