// Generated by @jxsuite/compiler — do not edit manually
import { reactive, computed, effect } from '@vue/reactivity';
import { render, html } from 'lit-html';

class SiteToolbar extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
    });
  }

  template() {
    const s = this.state;
    return html`
      <nav
        class="site-toolbar-0"
      >
        <a
          href="/"
          class="site-toolbar-1"
        >
          <img
            src="/favicon.svg"
            alt="Jx Suite"
            width="20"
            height="20"
          >
          Suite
        </a>
        <div
          class="site-toolbar-2"
        >
          <a
            href="/features"
            class="site-toolbar-3"
          >
            Features
          </a>
          <a
            href="/studio"
            class="site-toolbar-4"
          >
            Studio
          </a>
          <a
            href="/compare"
            class="site-toolbar-5"
          >
            Compare
          </a>
          <a
            href="/docs/getting-started"
            class="site-toolbar-6"
          >
            Docs
          </a>
          <a
            href="https://github.com/jxsuite/jx"
            target="_blank"
            rel="noopener noreferrer"
            class="site-toolbar-7"
          >
            GitHub
          </a>
        </div>
      </nav>
    `;
  }

  connectedCallback() {
    const _pa = this.getAttribute('data-jx-props');
    if (_pa) {
      try {
        const _p = JSON.parse(_pa);
        for (const [k, v] of Object.entries(_p)) {
          if (k in this.state) this.state[k] = v;
        }
      } catch {}
      this.removeAttribute('data-jx-props');
    }
    for (const key of Object.keys(this.state)) {
      if (this.hasOwnProperty(key) && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    if (this.hasAttribute('data-jx-prerendered')) {
      this.removeAttribute('data-jx-prerendered');
    }
    this.innerHTML = '';
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) { this.#dispose(); this.#dispose = null; }
  }
}

customElements.define('site-toolbar', SiteToolbar);
