/**
 * Compile-class.js — Compile .class.json schema-defined classes to JavaScript ES modules
 *
 * Generates proper ES modules with private fields, static members, accessors, etc. from a JSON
 * Schema 2020-12 class definition.
 */

import type { JxMutableNode } from "@jxsuite/schema/types";

/**
 * Compile a .class.json schema to a JavaScript ES module string.
 *
 * @param {JxMutableNode} classDef - Parsed .class.json content (must have $prototype: "Class")
 * @param {Record<string, unknown>} [_opts]
 * @returns {string} JavaScript module source code
 */
export function compileClassJson(classDef: JxMutableNode, _opts: Record<string, unknown> = {}) {
  const className = classDef.title;
  if (!className) throw new Error("compileClassJson: missing title (class name)");

  const baseClass = resolveBaseClass(classDef.extends);
  const defs = classDef.$defs as Record<string, unknown> | undefined;
  const fields = (defs?.fields ?? {}) as Record<string, JxMutableNode>;
  const ctor = defs?.constructor as JxMutableNode | undefined;
  const methods = (defs?.methods ?? {}) as Record<string, JxMutableNode>;

  const lines: string[] = [];
  lines.push("// Generated by @jxsuite/compiler from .class.json — do not edit manually");
  if (classDef.$id) lines.push(`// Source: ${classDef.$id}`);
  lines.push("");

  // Class declaration
  const extendsClause = baseClass !== "Object" ? ` extends ${baseClass}` : "";
  lines.push(`class ${className}${extendsClause} {`);

  // Static fields
  for (const [key, field] of Object.entries(fields)) {
    const f = field as JxMutableNode;
    if (f.scope !== "static") continue;
    const name = f.identifier ?? key;
    const prefix = f.access === "private" ? "#" : "";
    const initVal =
      f.initializer !== undefined
        ? JSON.stringify(f.initializer)
        : f.default !== undefined
          ? JSON.stringify(f.default)
          : "null";
    lines.push(`  static ${prefix}${name} = ${initVal};`);
  }

  // Instance field declarations (private)
  for (const [key, field] of Object.entries(fields)) {
    const f = field as JxMutableNode;
    if (f.scope === "static") continue;
    if (f.access !== "private") continue;
    const name = f.identifier ?? key;
    lines.push(`  #${name};`);
  }

  if (Object.keys(fields).length > 0) lines.push("");

  // Constructor
  lines.push("  constructor(config = {}) {");
  if (ctor?.superCall || baseClass !== "Object") {
    const superArgs = ctor?.superCall?.arguments ? ctor.superCall.arguments.join(", ") : "";
    lines.push(`    super(${superArgs});`);
  }

  // Initialize instance fields from config or defaults
  for (const [key, field] of Object.entries(fields)) {
    const f = field as JxMutableNode;
    if (f.scope === "static") continue;
    const name = f.identifier ?? key;
    const prefix = f.access === "private" ? "#" : "";
    const initVal =
      f.initializer !== undefined
        ? JSON.stringify(f.initializer)
        : f.default !== undefined
          ? JSON.stringify(f.default)
          : "null";
    lines.push(
      `    this.${prefix}${name} = config.${name} !== undefined ? config.${name} : ${initVal};`,
    );
  }

  // Constructor body statements
  if (ctor?.body) {
    const bodyLines = Array.isArray(ctor.body) ? ctor.body : [ctor.body];
    for (const line of bodyLines) {
      lines.push(`    ${line}`);
    }
  }
  lines.push("  }");

  // Methods
  for (const [key, method] of Object.entries(methods)) {
    const m = method as JxMutableNode;
    const name = m.identifier ?? key;
    const isStatic = m.scope === "static";
    const isPrivate = m.access === "private";
    const prefix = isPrivate ? "#" : "";
    const staticPrefix = isStatic ? "static " : "";
    const asyncPrefix =
      m.returnType?.$ref?.includes("Promise") ||
      isMethodAsync(m as unknown as { body?: string | string[] })
        ? "async "
        : "";

    const params = resolveParams(m.parameters ?? []);
    const bodyStr = resolveBody(m.body);

    lines.push("");

    if (m.role === "accessor") {
      // Getter
      if (m.getter) {
        lines.push(`  ${staticPrefix}get ${prefix}${name}() {`);
        lines.push(`    ${m.getter.body}`);
        lines.push("  }");
      }
      // Setter
      if (m.setter) {
        const setterParams = resolveParams(m.setter.parameters ?? []);
        lines.push(`  ${staticPrefix}set ${prefix}${name}(${setterParams}) {`);
        lines.push(`    ${m.setter.body}`);
        lines.push("  }");
      }
    } else {
      lines.push(`  ${staticPrefix}${asyncPrefix}${prefix}${name}(${params}) {`);
      for (const line of bodyStr) {
        lines.push(`    ${line}`);
      }
      lines.push("  }");
    }
  }

  lines.push("}");
  lines.push("");
  lines.push(`export { ${className} };`);
  lines.push(`export default ${className};`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Resolve the base class name from an extends value.
 *
 * @param {unknown} ext
 * @returns {string}
 */
function resolveBaseClass(ext: unknown) {
  if (!ext) return "Object";
  if (typeof ext === "string") return ext;
  const e = ext as JxMutableNode;
  if (e.$ref) {
    const ref = e.$ref;
    const match = ref.match(/([A-Za-z0-9_]+)\.class\.json/);
    return match ? match[1] : "Object";
  }
  return "Object";
}

/**
 * Resolve parameter names from $ref or inline definitions.
 *
 * @param {unknown[]} params
 * @returns {string}
 */
function resolveParams(params: unknown[]) {
  return params
    .map((p) => {
      const param = p as JxMutableNode;
      if (param.$ref) return param.$ref.split("/").pop();
      return param.identifier ?? param.name ?? "arg";
    })
    .join(", ");
}

/**
 * Resolve body from string or array of strings.
 *
 * @param {unknown} body
 * @returns {string[]}
 */
function resolveBody(body: unknown) {
  if (!body) return [""];
  if (Array.isArray(body)) return body;
  return [body as string];
}

/**
 * Simple heuristic: does the method body contain await?
 *
 * @param {{ body?: string | string[] }} method
 * @returns {boolean}
 */
function isMethodAsync(method: { body?: string | string[] }) {
  const body = Array.isArray(method.body) ? method.body.join("\n") : (method.body ?? "");
  return body.includes("await ");
}
