/**
 * Compile-server.js — Hono server handler compilation
 *
 * Compiles `timing: "server"` entries from a Jx document into a deployable Hono server handler
 * file.
 */

import $RefParser from "@apidevtools/json-schema-ref-parser";
import { collectServerEntries } from "../shared.js";

/**
 * Compile a Jx document to a Hono server handler file. The handler exposes each `timing: "server"`
 * entry as a POST endpoint under `/_jx/server/$export`. Returns null if no server entries are
 * found.
 *
 * @example
 *   const server = await compileServer("./dashboard.json");
 *   if (server) fs.writeFileSync("dist/server.js", server);
 *
 * @param {string | object} sourcePath - Path to .json file, URL, or raw object
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path for server endpoints. Default is `'/_jx/server'`
 * @returns {Promise<string | null>} Hono server handler source string, or null
 */
export async function compileServer(sourcePath, opts = {}) {
  const { baseUrl = "/_jx/server" } = opts;
  const doc = /** @type {JxElement} */ (await $RefParser.dereference(sourcePath));
  const entries = collectServerEntries(doc);
  if (entries.length === 0) return null;

  const imports = entries
    .map(({ exportName, src }) => `import { ${exportName} } from '${src}'`)
    .join("\n");

  const routes = entries.map(({ exportName }) => buildRoute(exportName, baseUrl)).join("\n");

  return `// Generated by @jxsuite/compiler — do not edit manually
// Deploy as a Cloudflare Worker, Node server, or Bun process.
// Requires: npm install hono

import { Hono } from 'hono'
${imports}

const app = new Hono()
${routes}

export default app
`;
}

/**
 * Generate a bundled Hono server entry from pre-collected server entries across an entire site.
 * Used when `build.adapter` is set in project.json. Returns null if no entries are provided.
 *
 * @param {{ exportName: string; src: string }[]} entries - Resolved server entries
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path for server endpoints. Default is `'/_jx/server'`
 * @param {string | null} [opts.adapter] - Deployment adapter: `"cloudflare"`, `"node"`, `"bun"`
 * @returns {string | null} Complete worker/server source string, or null
 */
export function compileSiteServer(entries, opts = {}) {
  const { baseUrl = "/_jx/server", adapter = null } = opts;
  if (entries.length === 0 && !adapter) return null;

  const imports = entries
    .map(({ exportName, src }) => `import { ${exportName} } from '${src}'`)
    .join("\n");

  const routes = entries.map(({ exportName }) => buildRoute(exportName, baseUrl)).join("\n");

  const adapterBlock =
    adapter === "cloudflare-workers"
      ? "\napp.all('*', (c) => c.env.ASSETS.fetch(c.req.raw))\n"
      : "\n";

  return `// Generated by @jxsuite/compiler — do not edit manually
import { Hono } from 'hono'
${imports}

const app = new Hono()
${routes}
${adapterBlock}
export default app
`;
}

/** @param {string} exportName @param {string} baseUrl */
function buildRoute(exportName, baseUrl) {
  return `
app.post('${baseUrl}/${exportName}', async (c) => {
  const args = await c.req.json().catch(() => ({}))
  try {
    return c.json(await ${exportName}(args, c.env))
  } catch (e) {
    return c.json({ ok: false, error: e?.message ?? 'Server error' }, 500)
  }
})`;
}

/**
 * Generate Cloudflare Pages Functions from pre-collected server entries. Returns a Map of relative
 * file paths (under `functions/`) to source strings.
 *
 * @param {{ exportName: string; src: string }[]} entries - Resolved server entries
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path prefix. Default is `'/_jx/server'`
 * @returns {Map<string, string>} Map of output path → source (e.g.
 *   `"functions/_jx/server/sendEmail.js"` → source)
 */
export function compilePagesFunctions(entries, opts = {}) {
  const { baseUrl = "/_jx/server" } = opts;
  const files = new Map();

  for (const { exportName, src } of entries) {
    const relativeSrc = src.startsWith("./") ? src : `./${src}`;
    const funcPath = `functions${baseUrl}/${exportName}.js`;
    const depth = funcPath.split("/").length - 1;
    const importPath = "../".repeat(depth) + relativeSrc.replace(/^\.\//, "");

    const source = `// Generated by @jxsuite/compiler — do not edit manually
import { ${exportName} } from '${importPath}'

export async function onRequestPost(context) {
  const args = await context.request.json().catch(() => ({}))
  try {
    const result = await ${exportName}(args, context.env)
    return Response.json(result)
  } catch (e) {
    return Response.json({ ok: false, error: e?.message ?? 'Server error' }, { status: 500 })
  }
}
`;
    files.set(funcPath, source);
  }

  return files;
}
