/**
 * Compile-server.js — Hono server handler compilation
 *
 * Compiles `timing: "server"` entries from a Jx document into a deployable Hono server handler
 * file.
 */

import { dereference } from "@apidevtools/json-schema-ref-parser";
import { collectServerEntries } from "../shared.ts";
import type { JxElement } from "@jxsuite/schema/types";

/**
 * Compile a Jx document to a Hono server handler file. The handler exposes each `timing: "server"`
 * entry as a POST endpoint under `/_jx/server/$export`. Returns null if no server entries are
 * found.
 *
 * @example
 *   const server = await compileServer("./dashboard.json");
 *   if (server) fs.writeFileSync("dist/server.js", server);
 *
 * @param {string | object} sourcePath - Path to .json file, URL, or raw object
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path for server endpoints. Default is `'/_jx/server'`
 * @returns {Promise<string | null>} Hono server handler source string, or null
 */
export async function compileServer(
  sourcePath: string | object,
  opts: {
    baseUrl?: string;
  } = {},
) {
  const { baseUrl = "/_jx/server" } = opts;
  const doc = (await dereference(sourcePath)) as JxElement;
  const entries = collectServerEntries(doc);
  if (entries.length === 0) {
    return null;
  }

  const imports = entries
    .map(({ exportName, src }) => `import { ${exportName} } from '${src}'`)
    .join("\n");

  const routes = entries.map(({ exportName }) => buildRoute(exportName, baseUrl)).join("\n");

  return `// Generated by @jxsuite/compiler — do not edit manually
// Deploy as a Cloudflare Worker, Node server, or Bun process.
// Requires: npm install hono

import { Hono } from 'hono'
${imports}

const app = new Hono()
${routes}

export default app
`;
}

/**
 * Generate a bundled Hono server entry from pre-collected server entries across an entire site.
 * Used when `build.adapter` is set in project.json. Returns null if no entries are provided.
 *
 * @param {{ exportName: string; src: string }[]} entries - Resolved server entries
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path for server endpoints. Default is `'/_jx/server'`
 * @param {string | null} [opts.adapter] - Deployment adapter: `"cloudflare-workers"`,
 *   `"cloudflare-pages"`, `"node"`, `"bun"`
 * @returns {string | null} Complete worker/server source string, or null
 */
export function compileSiteServer(
  entries: { exportName: string; src: string }[],
  opts: {
    baseUrl?: string;
    adapter?: string | null;
  } = {},
) {
  const { baseUrl = "/_jx/server", adapter = null } = opts;
  if (entries.length === 0 && !adapter) {
    return null;
  }

  const imports = entries
    .map(({ exportName, src }) => `import { ${exportName} } from '${src}'`)
    .join("\n");

  const routes = entries.map(({ exportName }) => buildRoute(exportName, baseUrl)).join("\n");

  // Workers static assets and Pages advanced mode (_worker.js) both route every request
  // Through the worker — unmatched paths must fall through to the ASSETS binding.
  const adapterBlock =
    adapter === "cloudflare-workers" || adapter === "cloudflare-pages"
      ? "\napp.all('*', (c) => c.env.ASSETS.fetch(c.req.raw))\n"
      : "\n";

  return `// Generated by @jxsuite/compiler — do not edit manually
import { Hono } from 'hono'
${imports}

const app = new Hono()
${routes}
${adapterBlock}
export default app
`;
}

/** @param {string} exportName @param {string} baseUrl */
function buildRoute(exportName: string, baseUrl: string) {
  return `
app.post('${baseUrl}/${exportName}', async (c) => {
  const args = await c.req.json().catch(() => ({}))
  try {
    return c.json(await ${exportName}(args, c.env))
  } catch (e) {
    return c.json({ ok: false, error: e?.message ?? 'Server error' }, 500)
  }
})`;
}
