/**
 * Compile-image-endpoint.js — Cloudflare Images binding endpoint codegen
 *
 * Generates the `/_jx/image` runtime image-transformation handler used when `images.service:
 * "cloudflare"` is set in project.json. The handler fetches the original static asset via the
 * ASSETS binding and pipes it through the Cloudflare Images binding, negotiating the output format
 * from the request's Accept header.
 */

import type { ImageConfig } from "../site/image-optimizer.ts";

const MIME: Record<string, string> = {
  avif: "image/avif",
  webp: "image/webp",
  jpeg: "image/jpeg",
  png: "image/png",
};

/**
 * Generate the shared `jxHandleImage(request, env, waitUntil)` handler source. Widths, format
 * preference order (avif first, mirroring the build-time pipeline), per-format quality, and the
 * Images binding name are baked in at codegen time.
 *
 * @param {ImageConfig} images - The project's images config
 * @returns {string} JavaScript source defining `jxHandleImage`
 */
export function buildImageHandlerSource(images: ImageConfig) {
  const binding = images.binding ?? "IMAGES";
  const formats = [...(images.formats ?? [])]
    .filter((f) => f in MIME)
    .sort((a, b) => Number(b === "avif") - Number(a === "avif"));
  const tuples = formats.map((f) => [
    MIME[f],
    images.quality?.[f as keyof ImageConfig["quality"]] ?? 80,
  ]);

  return `const JX_IMG_WIDTHS = new Set(${JSON.stringify(images.widths ?? [])})
const JX_IMG_FORMATS = ${JSON.stringify(tuples)} // [mime, quality] in preference order
const JX_IMG_BINDING = ${JSON.stringify(binding)}

async function jxHandleImage(request, env, waitUntil) {
  const url = new URL(request.url)
  const src = url.searchParams.get('src') ?? ''
  const w = Number(url.searchParams.get('w') ?? '')

  // Same-origin asset paths only — never act as an open proxy.
  if (!src.startsWith('/') || src.startsWith('//') || src.includes('..') ||
      src.includes(':') || src.includes('\\\\') || src.includes('?') || src.includes('#')) {
    return new Response('Invalid src', { status: 400 })
  }
  if (!JX_IMG_WIDTHS.has(w)) return new Response('Invalid width', { status: 400 })

  const accept = request.headers.get('accept') ?? ''
  let target = null
  for (const [mime, quality] of JX_IMG_FORMATS) {
    if (accept.includes(mime)) { target = { mime, quality }; break }
  }

  const v = url.searchParams.get('v') ?? ''
  const cacheKey = new Request(url.origin + '/_jx/image?src=' + encodeURIComponent(src) +
    '&w=' + w + '&f=' + (target ? target.mime : 'orig') + '&v=' + encodeURIComponent(v))
  const cache = caches.default
  const hit = await cache.match(cacheKey)
  if (hit) {
    const out = new Response(hit.body, hit)
    out.headers.set('Vary', 'Accept')
    return out
  }

  const asset = await env.ASSETS.fetch(new Request(new URL(src, url.origin)))
  if (!asset.ok || !asset.body) return new Response('Not found', { status: 404 })

  let response
  if (target && env[JX_IMG_BINDING]) {
    try {
      const result = await env[JX_IMG_BINDING]
        .input(asset.body)
        .transform({ width: w })
        .output({ format: target.mime, quality: target.quality })
      response = result.response()
    } catch (e) {
      // Transform failed — serve the original asset untouched.
      const retry = await env.ASSETS.fetch(new Request(new URL(src, url.origin)))
      response = new Response(retry.body, retry)
    }
  } else {
    response = new Response(asset.body, asset)
  }

  response = new Response(response.body, response)
  response.headers.set('Cache-Control', 'public, max-age=31536000, immutable')
  if (waitUntil) waitUntil(cache.put(cacheKey, response.clone()))
  response.headers.set('Vary', 'Accept')
  return response
}`;
}

/**
 * Generate the Hono route registering `jxHandleImage` at `/_jx/image`. Must be injected before the
 * cloudflare-workers `app.all('*')` ASSETS catch-all.
 *
 * @returns {string}
 */
export function buildImageWorkerRoute() {
  return `
app.get('/_jx/image', (c) => jxHandleImage(c.req.raw, c.env, (p) => c.executionCtx?.waitUntil?.(p)))`;
}

/**
 * Generate a complete Cloudflare Pages Function (`functions/_jx/image.js`) wrapping `jxHandleImage`
 * in an `onRequestGet` handler.
 *
 * @param {ImageConfig} images - The project's images config
 * @returns {string}
 */
export function compilePagesImageFunction(images: ImageConfig) {
  return `// Generated by @jxsuite/compiler — do not edit manually
${buildImageHandlerSource(images)}

export async function onRequestGet(context) {
  return jxHandleImage(context.request, context.env, (p) => context.waitUntil(p))
}
`;
}
