import { describe, test, expect } from "bun:test";
import {
  compileServer,
  compileSiteServer,
  compilePagesFunctions,
} from "../src/targets/compile-server";

// ─── compileServer ─────────────────────────────────────────────────────────

describe("compileServer", () => {
  test("returns null when no server entries exist", async () => {
    const doc = {
      tagName: "div",
      children: [{ tagName: "p", textContent: "No server entries" }],
    };
    const result = await compileServer(doc);
    expect(result).toBeNull();
  });

  test("generates Hono handler for server entries", async () => {
    const doc = {
      tagName: "div",
      state: {
        getData: {
          timing: "server",
          $src: "./api/get-data.js",
          $export: "getData",
        },
      },
      children: [],
    };
    const result = await compileServer(doc);
    expect(result).not.toBeNull();
    expect(result).toContain("import { Hono } from 'hono'");
    expect(result).toContain("import { getData } from './api/get-data.js'");
    expect(result).toContain("app.post('/_jx/server/getData'");
    expect(result).toContain("export default app");
  });

  test("supports custom baseUrl option", async () => {
    const doc = {
      state: {
        myFunc: {
          timing: "server",
          $src: "./handlers.js",
          $export: "myFunc",
        },
      },
    };
    const result = await compileServer(doc, { baseUrl: "/api" });
    expect(result).toContain("app.post('/api/myFunc'");
  });

  test("generates multiple routes for multiple server entries", async () => {
    const doc = {
      state: {
        fetchUser: {
          timing: "server",
          $src: "./user.js",
          $export: "fetchUser",
        },
        saveUser: {
          timing: "server",
          $src: "./user.js",
          $export: "saveUser",
        },
      },
    };
    const result = await compileServer(doc);
    expect(result).toContain("app.post('/_jx/server/fetchUser'");
    expect(result).toContain("app.post('/_jx/server/saveUser'");
    expect(result).toContain("import { fetchUser } from './user.js'");
    expect(result).toContain("import { saveUser } from './user.js'");
  });

  test("generated code includes json parsing", async () => {
    const doc = {
      state: {
        handler: {
          timing: "server",
          $src: "./api.js",
          $export: "handler",
        },
      },
    };
    const result = await compileServer(doc);
    expect(result).toContain("c.req.json()");
    expect(result).toContain("c.json(await handler(args, c.env))");
  });

  test("wraps handlers in try/catch", async () => {
    const doc = {
      state: {
        fn: {
          timing: "server",
          $src: "./fn.js",
          $export: "fn",
        },
      },
    };
    const result = await compileServer(doc);
    expect(result).toContain("try {");
    expect(result).toContain("catch (e)");
    expect(result).toContain("ok: false");
  });

  test("includes do-not-edit comment", async () => {
    const doc = {
      state: {
        fn: {
          timing: "server",
          $src: "./fn.js",
          $export: "fn",
        },
      },
    };
    const result = await compileServer(doc);
    expect(result).toContain("Generated by @jxsuite/compiler");
    expect(result).toContain("do not edit manually");
  });
});

// ─── compileSiteServer ────────────────────────────────────────────────────

describe("compileSiteServer", () => {
  test("returns null for empty entries", () => {
    expect(compileSiteServer([])).toBeNull();
  });

  test("generates Hono handler from pre-collected entries", () => {
    const entries = [{ exportName: "sendEmail", src: "./components/contact.server.js" }];
    const result = compileSiteServer(entries);
    expect(result).toContain("import { Hono } from 'hono'");
    expect(result).toContain("import { sendEmail } from './components/contact.server.js'");
    expect(result).toContain("app.post('/_jx/server/sendEmail'");
    expect(result).toContain("sendEmail(args, c.env)");
    expect(result).toContain("export default app");
  });

  test("passes c.env and includes try/catch", () => {
    const entries = [{ exportName: "fn", src: "./fn.js" }];
    const result = compileSiteServer(entries);
    expect(result).toContain("fn(args, c.env)");
    expect(result).toContain("try {");
    expect(result).toContain("catch (e)");
    expect(result).toContain("ok: false");
  });

  test("cloudflare-workers adapter adds asset fallback", () => {
    const entries = [{ exportName: "fn", src: "./fn.js" }];
    const result = compileSiteServer(entries, {
      adapter: "cloudflare-workers",
    });
    expect(result).toContain("c.env.ASSETS.fetch(c.req.raw)");
  });

  test("node adapter does not add asset fallback", () => {
    const entries = [{ exportName: "fn", src: "./fn.js" }];
    const result = compileSiteServer(entries, { adapter: "node" });
    expect(result).not.toContain("ASSETS.fetch");
  });

  test("null adapter does not add asset fallback", () => {
    const entries = [{ exportName: "fn", src: "./fn.js" }];
    const result = compileSiteServer(entries);
    expect(result).not.toContain("ASSETS.fetch");
  });

  test("generates multiple routes", () => {
    const entries = [
      { exportName: "fnA", src: "./a.js" },
      { exportName: "fnB", src: "./b.js" },
    ];
    const result = compileSiteServer(entries, {
      adapter: "cloudflare-workers",
    });
    expect(result).toContain("app.post('/_jx/server/fnA'");
    expect(result).toContain("app.post('/_jx/server/fnB'");
    expect(result).toContain("import { fnA } from './a.js'");
    expect(result).toContain("import { fnB } from './b.js'");
  });

  test("supports custom baseUrl", () => {
    const entries = [{ exportName: "fn", src: "./fn.js" }];
    const result = compileSiteServer(entries, { baseUrl: "/api" });
    expect(result).toContain("app.post('/api/fn'");
  });
});

// ─── compilePagesFunctions ────────────────────────────────────────────────────

describe("compilePagesFunctions", () => {
  test("returns a Map of file paths to source strings", () => {
    const entries = [{ exportName: "sendEmail", src: "./components/contact.server.js" }];
    const result = compilePagesFunctions(entries);
    expect(result).toBeInstanceOf(Map);
    expect(result.size).toBe(1);
  });

  test("generates correct file path under functions/", () => {
    const entries = [{ exportName: "sendEmail", src: "./components/contact.server.js" }];
    const result = compilePagesFunctions(entries);
    expect(result.has("functions/_jx/server/sendEmail.js")).toBe(true);
  });

  test("uses onRequestPost with context parameter", () => {
    const entries = [{ exportName: "sendEmail", src: "./components/contact.server.js" }];
    const result = compilePagesFunctions(entries);
    const source = result.get("functions/_jx/server/sendEmail.js");
    expect(source).toContain("export async function onRequestPost(context)");
  });

  test("uses native Response.json instead of Hono", () => {
    const entries = [{ exportName: "sendEmail", src: "./components/contact.server.js" }];
    const result = compilePagesFunctions(entries);
    const source = result.get("functions/_jx/server/sendEmail.js");
    expect(source).toContain("Response.json(result)");
    expect(source).toContain("Response.json({ ok: false");
    expect(source).not.toContain("Hono");
    expect(source).not.toContain("c.json");
  });

  test("passes context.env to the server function", () => {
    const entries = [{ exportName: "sendEmail", src: "./components/contact.server.js" }];
    const result = compilePagesFunctions(entries);
    const source = result.get("functions/_jx/server/sendEmail.js");
    expect(source).toContain("sendEmail(args, context.env)");
  });

  test("generates correct relative import path", () => {
    const entries = [{ exportName: "sendEmail", src: "./components/contact.server.js" }];
    const result = compilePagesFunctions(entries);
    const source = result.get("functions/_jx/server/sendEmail.js");
    expect(source).toContain("from '../../../components/contact.server.js'");
  });

  test("generates multiple function files", () => {
    const entries = [
      { exportName: "sendEmail", src: "./components/contact.server.js" },
      { exportName: "submitForm", src: "./components/form.server.js" },
    ];
    const result = compilePagesFunctions(entries);
    expect(result.size).toBe(2);
    expect(result.has("functions/_jx/server/sendEmail.js")).toBe(true);
    expect(result.has("functions/_jx/server/submitForm.js")).toBe(true);
  });

  test("returns empty Map when no entries", () => {
    const result = compilePagesFunctions([]);
    expect(result.size).toBe(0);
  });

  test("supports custom baseUrl", () => {
    const entries = [{ exportName: "fn", src: "./fn.js" }];
    const result = compilePagesFunctions(entries, { baseUrl: "/api" });
    expect(result.has("functions/api/fn.js")).toBe(true);
  });
});
