import { describe, test, expect } from "bun:test";
import {
  buildImageHandlerSource,
  buildImageWorkerRoute,
  compilePagesImageFunction,
} from "../src/targets/compile-image-endpoint";
import { compileSiteServer } from "../src/targets/compile-server";

const images = {
  optimize: true,
  widths: [640, 1280],
  formats: ["webp", "avif"],
  quality: { webp: 75, avif: 60, jpeg: 80, png: 80 },
  sizes: "100vw",
  lazyLoad: true,
  service: "cloudflare" as const,
};

// ─── buildImageHandlerSource ───────────────────────────────────────────────

describe("buildImageHandlerSource", () => {
  test("bakes configured widths into a whitelist Set", () => {
    const src = buildImageHandlerSource(images);
    expect(src).toContain("const JX_IMG_WIDTHS = new Set([640,1280])");
    expect(src).toContain("Invalid width");
  });

  test("orders format tuples avif-first with configured quality", () => {
    const src = buildImageHandlerSource(images);
    expect(src).toContain('const JX_IMG_FORMATS = [["image/avif",60],["image/webp",75]]');
  });

  test("defaults to the IMAGES binding name", () => {
    const src = buildImageHandlerSource(images);
    expect(src).toContain('const JX_IMG_BINDING = "IMAGES"');
  });

  test("respects a custom binding name", () => {
    const src = buildImageHandlerSource({ ...images, binding: "MY_IMAGES" });
    expect(src).toContain('const JX_IMG_BINDING = "MY_IMAGES"');
  });

  test("validates src to prevent open-proxy use", () => {
    const src = buildImageHandlerSource(images);
    expect(src).toContain("Invalid src");
    expect(src).toContain("!src.startsWith('/')");
    expect(src).toContain("src.startsWith('//')");
    expect(src).toContain("src.includes('..')");
  });

  test("transforms via the Images binding and caches at the edge", () => {
    const src = buildImageHandlerSource(images);
    expect(src).toContain(".input(asset.body)");
    expect(src).toContain(".transform({ width: w })");
    expect(src).toContain(".output({ format: target.mime, quality: target.quality })");
    expect(src).toContain("caches.default");
    expect(src).toContain("'Cache-Control', 'public, max-age=31536000, immutable'");
    expect(src).toContain("'Vary', 'Accept'");
    expect(src).toContain("env.ASSETS.fetch");
  });

  test("ignores unknown formats", () => {
    const src = buildImageHandlerSource({
      ...images,
      formats: ["webp", "tiff"],
    });
    expect(src).toContain('const JX_IMG_FORMATS = [["image/webp",75]]');
  });

  test("falls back to quality 80 when unset", () => {
    const src = buildImageHandlerSource({ ...images, quality: {} });
    expect(src).toContain('[["image/avif",80],["image/webp",80]]');
  });
});

// ─── compilePagesImageFunction ─────────────────────────────────────────────

describe("compilePagesImageFunction", () => {
  test("wraps the handler in an onRequestGet Pages function", () => {
    const src = compilePagesImageFunction(images);
    expect(src).toContain("// Generated by @jxsuite/compiler");
    expect(src).toContain("async function jxHandleImage(request, env, waitUntil)");
    expect(src).toContain("export async function onRequestGet(context)");
    expect(src).toContain(
      "jxHandleImage(context.request, context.env, (p) => context.waitUntil(p))",
    );
  });
});

// ─── compileSiteServer integration ─────────────────────────────────────────

describe("compileSiteServer with images", () => {
  test("registers the image route before the ASSETS catch-all", () => {
    const result = compileSiteServer([], {
      adapter: "cloudflare-workers",
      images,
    });
    expect(result).not.toBeNull();
    const imageRoute = result!.indexOf("app.get('/_jx/image'");
    const catchAll = result!.indexOf("app.all('*'");
    expect(imageRoute).toBeGreaterThan(-1);
    expect(catchAll).toBeGreaterThan(-1);
    expect(imageRoute).toBeLessThan(catchAll);
  });

  test("embeds the handler and guards executionCtx for non-Workers runtimes", () => {
    const result = compileSiteServer([], {
      adapter: "cloudflare-workers",
      images,
    });
    expect(result).toContain("async function jxHandleImage(request, env, waitUntil)");
    expect(result).toContain("c.executionCtx?.waitUntil?.(p)");
  });

  test("output is unchanged when images is not passed", () => {
    const withNull = compileSiteServer([], {
      adapter: "cloudflare-workers",
      images: null,
    });
    const without = compileSiteServer([], { adapter: "cloudflare-workers" });
    expect(withNull).toBe(without!);
    expect(without).not.toContain("/_jx/image");
    expect(without).not.toContain("jxHandleImage");
  });

  test("buildImageWorkerRoute targets /_jx/image", () => {
    expect(buildImageWorkerRoute()).toContain("app.get('/_jx/image'");
  });

  test("coexists with server entry routes", () => {
    const result = compileSiteServer([{ exportName: "sendEmail", src: "./components/email.js" }], {
      adapter: "cloudflare-workers",
      images,
    });
    expect(result).toContain("app.post('/_jx/server/sendEmail'");
    expect(result).toContain("app.get('/_jx/image'");
    expect(result).toContain("import { sendEmail } from './components/email.js'");
  });
});
