/**
 * MSIX package identity — the one place the Windows publisher subject is written down.
 *
 * MSIX signing enforces an EXACT string match between the `<Identity Publisher>` in
 * AppxManifest.xml and the Subject of the signing certificate. Any mismatch fails at `signtool
 * sign` (and again at `Add-AppxPackage`), so the two values cannot be allowed to drift.
 *
 * They had drifted. `sign-cert.ts` used to read the publisher from the electrobun config via
 * `electrobun-builder-for-windows`'s `loadConfig()` — but that helper only jiti-imports
 * `electrobun.config.ts` and returns its default export, and THIS package's config is `satisfies
 * ElectrobunConfig` from `electrobun`, a shape with no `windows.msix` key at all. So
 * `config.windows?.msix?.publisher` was always `undefined`, the `?? "CN=Jx Studio Dev"` fallback
 * always won, and the generated cert could never have signed the manifest below (which carries the
 * Partner Center publisher ID). That never surfaced because the working cert is committed at
 * `certs/jx-studio-dev.pfx` — subject `CN=118A192A-…`, generated by hand — and sign-cert.ts
 * short-circuits on `existsSync`, so the broken branch was only ever reachable on a fresh clone
 * that deleted the cert, where build-msix.ts's `catch` would have swallowed it into "⚠ Signing
 * FAILED — shipping an UNSIGNED MSIX".
 *
 * Hence: one exported constant, consumed by both the manifest and the cert generator.
 */

/**
 * The Partner Center-assigned publisher ID for the Store listing. Both the manifest `Identity` and
 * the dev certificate's Subject use it verbatim.
 *
 * Do NOT change this to a friendly name: the Store rejects a submission whose Identity does not
 * match the value assigned in Partner Center. A self-signed dev cert may carry any Subject, so it
 * is the cert that follows the manifest, never the other way around.
 */
export const MSIX_PUBLISHER = "CN=118A192A-BE3D-4B35-A22B-EA889CD1D0B4";

/** Store-assigned package identity name. Also fixed by Partner Center. */
export const MSIX_IDENTITY_NAME = "AvunuLLC.JxStudio";

/** Human-readable publisher, shown in the installer UI and Settings → Apps. */
export const MSIX_PUBLISHER_DISPLAY_NAME = "Avunu LLC";

/**
 * Dev signing certificate. `scripts/trust-cert.ps1` repeats both values as PowerShell literals — it
 * cannot import this module — so update it alongside any change here.
 */
export const DEV_CERT_FILENAME = "jx-studio-dev.pfx";
export const DEV_CERT_PASSWORD = "dev-cert-password";

/**
 * MSIX requires a four-part `Major.Minor.Build.Revision` version, while package.json carries three.
 * Used for the manifest AND the artifact filename, so both agree.
 */
export function toQuadVersion(version: string): string {
  return version.split(".").length === 3 ? `${version}.0` : version;
}

/** Renders AppxManifest.xml. Backslashes in asset paths are literal — MSIX wants Windows separators. */
export function renderAppxManifest(version: string): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
         xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
         xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities">

  <Identity Name="${MSIX_IDENTITY_NAME}"
            Publisher="${MSIX_PUBLISHER}"
            Version="${toQuadVersion(version)}"
            ProcessorArchitecture="x64" />

  <Properties>
    <DisplayName>Jx Studio</DisplayName>
    <PublisherDisplayName>${MSIX_PUBLISHER_DISPLAY_NAME}</PublisherDisplayName>
    <Logo>Assets\\StoreLogo.png</Logo>
  </Properties>

  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.26100.0" />
  </Dependencies>

  <Resources>
    <Resource Language="en-US" />
  </Resources>

  <Applications>
    <Application Id="App" Executable="bin\\launcher.exe" EntryPoint="Windows.FullTrustApplication">
      <uap:VisualElements DisplayName="Jx Studio"
                          Description="Jx Studio"
                          BackgroundColor="transparent"
                          Square150x150Logo="Assets\\Square150x150Logo.png"
                          Square44x44Logo="Assets\\Square44x44Logo.png">
        <uap:DefaultTile Wide310x150Logo="Assets\\Wide310x150Logo.png" />
        <uap:SplashScreen Image="Assets\\SplashScreen.png" />
      </uap:VisualElements>
    </Application>
  </Applications>

  <Capabilities>
    <Capability Name="internetClient" />
    <rescap:Capability Name="runFullTrust" />
  </Capabilities>
</Package>
`;
}
