// Shared bits for the docs reference generators.

/** Marker every generated page must carry (check-doc-refs.ts enforces it). */
export const BANNER =
  "<!-- GENERATED by scripts/docs/generate-reference.ts — do not edit; run `bun run docs:generate`. -->";

/** Render docs frontmatter with the generated flag. */
export function frontmatter(fields: { title: string; description: string }): string {
  return [
    "---",
    `title: "${fields.title}"`,
    `description: "${fields.description}"`,
    "generated: true",
    "---",
  ].join("\n");
}
