export const BUILT_IN_PROTOTYPES = [
  "Function",
  "Request",
  "URLSearchParams",
  "FormData",
  "LocalStorage",
  "SessionStorage",
  "Cookie",
  "IndexedDB",
  "Array",
  "Set",
  "Map",
  "Blob",
  "ReadableStream",
] as const;

export const externalClassDefSchema = {
  description:
    'An external class / data source. $prototype is a constructor name (not "Function"). ' +
    "When $prototype is not in the built-in registry, $src is required. " +
    "All state entries are reactive by default.",
  properties: {
    $export: {
      description: "Named export in $src module. Defaults to the $prototype value.",
      type: "string",
    },
    $prototype: {
      description: "Constructor name — built-in Web API class or external class name.",
      examples: [
        "Request",
        "URLSearchParams",
        "FormData",
        "LocalStorage",
        "SessionStorage",
        "Cookie",
        "IndexedDB",
        "Array",
        "Set",
        "Map",
        "Blob",
        "ReadableStream",
        "MarkdownCollection",
        "MyParser",
      ],
      not: { const: "Function" },
      type: "string",
    },
    $src: {
      description: "External module specifier. Required when $prototype is not a built-in.",
      examples: ["@jxsuite/md", "./lib/my-parser.js", "npm:@myorg/data"],
      type: "string",
    },
    autoIncrement: { type: "boolean" },
    body: {},
    database: { type: "string" },
    debounce: { minimum: 0, type: "integer" },
    default: {},
    description: { type: "string" },
    domain: { type: "string" },
    expires: { type: "string" },
    filter: { $ref: "#/$defs/RefObject" },
    headers: { additionalProperties: { type: "string" }, type: "object" },
    indexes: {
      items: {
        properties: {
          keyPath: {
            oneOf: [{ type: "string" }, { items: { type: "string" }, type: "array" }],
          },
          name: { type: "string" },
          unique: { type: "boolean" },
        },
        required: ["name", "keyPath"],
        type: "object",
      },
      type: "array",
    },
    items: {},
    key: { type: "string" },
    keyPath: { type: "string" },
    manual: { type: "boolean" },
    map: { $ref: "#/$defs/ElementDef" },
    maxAge: { type: "integer" },
    method: {
      enum: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
      type: "string",
    },
    name: { type: "string" },
    path: { type: "string" },
    responseType: {
      enum: ["json", "text", "blob", "arraybuffer", "document", ""],
      type: "string",
    },
    sameSite: { enum: ["strict", "lax", "none"], type: "string" },
    secure: { type: "boolean" },
    sort: { $ref: "#/$defs/RefObject" },
    src: {
      description: "Configuration property passed to external class constructor.",
      type: "string",
    },
    store: { type: "string" },
    timing: { enum: ["compiler", "server", "client"], type: "string" },
    url: { $ref: "#/$defs/StringOrRef" },
    version: { minimum: 1, type: "integer" },
  },
  required: ["$prototype"],
  type: "object",
} as const;
