[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["**/tests/**", "./result/**", "../schema/**"]
coverageThreshold = { lines = 0.99, functions = 0.99 }
