name: Publish to npm
permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      tag_name:
        description: Tag to build and publish.
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.tag_name }}
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@latest
      - run: bun install
      - run: bun run build
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/ai
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/schema
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/runtime
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/parser
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/compiler
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/server
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/studio
      - run: |
          bun pm pack
          npm publish --provenance *.tgz
        working-directory: packages/create
